$(document).ready(function () {
    $("#replace_btn").click(function () {
        let new_text = $("#original_text").val();
        new_text = new_text.replace(/:I/g, "Ϊ");
        new_text = new_text.replace(/:Y/g, "Ϋ");
        new_text = new_text.replace(/:i/g, "ϊ");
        new_text = new_text.replace(/:y/g, "ϋ");
        new_text = new_text.replace(/;A/g, "Ά");
        new_text = new_text.replace(/;a/g, "ά");
        new_text = new_text.replace(/;E/g, "Έ");
        new_text = new_text.replace(/;e/g, "έ");
        new_text = new_text.replace(/;H/g, "Ή");
        new_text = new_text.replace(/;h/g, "ή");
        new_text = new_text.replace(/;I/g, "Ί");
        new_text = new_text.replace(/;i/g, "ί");
        new_text = new_text.replace(/;O/g, "Ό");
        new_text = new_text.replace(/;o/g, "ό");
        new_text = new_text.replace(/;Y/g, "Ύ");
        new_text = new_text.replace(/;y/g, "ύ");
        new_text = new_text.replace(/;V/g, "Ώ");
        new_text = new_text.replace(/;v/g, "ώ");
        new_text = new_text.replace(/Wi/g, "ΐ");
        new_text = new_text.replace(/Wy/g, "ΰ");
        new_text = new_text.replace(/;i/g, "ί");
        new_text = new_text.replace(/;A/g, "Ά");
        new_text = new_text.replace(/Wy/g, "ΰ");
        new_text = new_text.replace(/:y/g, "ϋ"); 
        new_text = new_text.replace(/w/g, "ς");
        new_text = new_text.replace(/e/g, "ε");
        new_text = new_text.replace(/r/g, "ρ");
        new_text = new_text.replace(/t/g, "τ");
        new_text = new_text.replace(/y/g, "υ");
        new_text = new_text.replace(/u/g, "θ");
        new_text = new_text.replace(/i/g, "ι");
        new_text = new_text.replace(/o/g, "ο");
        new_text = new_text.replace(/p/g, "π");
        new_text = new_text.replace(/a/g, "α");
        new_text = new_text.replace(/s/g, "σ");
        new_text = new_text.replace(/d/g, "δ");
        new_text = new_text.replace(/f/g, "φ");
        new_text = new_text.replace(/g/g, "γ");
        new_text = new_text.replace(/h/g, "η");
        new_text = new_text.replace(/j/g, "ξ");
        new_text = new_text.replace(/k/g, "κ");
        new_text = new_text.replace(/l/g, "λ");
        new_text = new_text.replace(/z/g, "ζ");
        new_text = new_text.replace(/x/g, "χ");
        new_text = new_text.replace(/c/g, "ψ");
        new_text = new_text.replace(/v/g, "ω");
        new_text = new_text.replace(/b/g, "β");
        new_text = new_text.replace(/n/g, "ν");
        new_text = new_text.replace(/m/g, "μ");
        new_text = new_text.replace(/E/g, "Ε");
        new_text = new_text.replace(/R/g, "Ρ");
        new_text = new_text.replace(/T/g, "Τ");
        new_text = new_text.replace(/Y/g, "Υ");
        new_text = new_text.replace(/U/g, "Θ");
        new_text = new_text.replace(/I/g, "Ι");
        new_text = new_text.replace(/O/g, "Ο");
        new_text = new_text.replace(/P/g, "Π");
        new_text = new_text.replace(/A/g, "Α");
        new_text = new_text.replace(/S/g, "Σ");
        new_text = new_text.replace(/D/g, "Δ");
        new_text = new_text.replace(/F/g, "Φ");
        new_text = new_text.replace(/G/g, "Γ");
        new_text = new_text.replace(/H/g, "Η");
        new_text = new_text.replace(/J/g, "Ξ");
        new_text = new_text.replace(/K/g, "Κ");
        new_text = new_text.replace(/L/g, "Λ");
        new_text = new_text.replace(/Z/g, "Ζ");
        new_text = new_text.replace(/X/g, "Χ");
        new_text = new_text.replace(/C/g, "Ψ");
        new_text = new_text.replace(/V/g, "Ω");
        new_text = new_text.replace(/B/g, "Β");
        new_text = new_text.replace(/N/g, "Ν");
        new_text = new_text.replace(/M/g, "Μ");        
        $("#new_text").val(new_text);

        return false;
    });
});

